# Generated by Django 3.1.14 on 2022-07-01 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220701_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='file',
        ),
        migrations.AlterField(
            model_name='order',
            name='datetimestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 1, 6, 26, 21, 342885)),
        ),
    ]
